# Environment settings
width: 100
height: 100

# Agent settings
system_agents: 0
independent_agents: 50
initial_resource_level: 12
max_population: 300
starvation_threshold: 0
max_starvation_time: 15
offspring_cost: 6
min_reproduction_resources: 10
offspring_initial_resources: 5

# Resource settings
initial_resources: 60
resource_regen_rate: 0.1
resource_regen_amount: 2
max_resource_amount: 30

# Agent behavior settings
base_consumption_rate: 0.1
max_movement: 8
gathering_range: 20
max_gather_amount: 3
territory_range: 30

# Learning parameters
learning_rate: 0.001
gamma: 0.95
epsilon_start: 1.0
epsilon_min: 0.01
epsilon_decay: 0.995
memory_size: 32
batch_size: 32
training_frequency: 4
dqn_hidden_size: 24

# Visualization settings
visualization:
  canvas_size: [400, 400]
  padding: 20
  background_color: "black"
  max_animation_frames: 5
  animation_min_delay: 50
  max_resource_amount: 30
  resource_colors:
    glow_red: 150
    glow_green: 255
    glow_blue: 50
  resource_size: 2
  agent_radius_scale: 2
  birth_radius_scale: 4
  death_mark_scale: 1.5
  agent_colors:
    SystemAgent: "blue"
    IndependentAgent: "red"
  min_font_size: 10
  font_scale_factor: 40
  font_family: "arial"
  death_mark_color: [255, 0, 0]
  birth_mark_color: [255, 255, 255]
  metric_colors:
    total_agents: "#4a90e2"
    system_agents: "#50c878"
    independent_agents: "#e74c3c"
    total_resources: "#f39c12"
    average_agent_resources: "#9b59b6" 