# ===== AGENTFARM CONFIGURATION =====
# Modern profile-based configuration system
# Uses reusable profiles to eliminate duplication

# === SIMULATION BASICS ===
simulation_steps: 1000
max_population: 300
seed: 1234567890

# === PROFILES ===
# Use predefined profiles for common patterns
environment_profile: "default"  # default, resource_rich, resource_scarce, large_world, small_world, dynamic
default_dqn_profile: "stable_learning"  # default, fast_learning, stable_learning, exploration_focused, memory_efficient, high_performance

# === AGENTS ===
# Define agent types and their behavior
agents:
  system:
    behavior_profile: "cooperative"  # cooperative, aggressive, balanced, gatherer, explorer, survivor
    dqn_profile: "stable_learning"
    count: 10
    initial_resources: 5
    
  independent:
    behavior_profile: "aggressive"
    dqn_profile: "fast_learning"
    count: 10
    initial_resources: 5
    
  control:
    behavior_profile: "balanced"
    count: 10
    initial_resources: 5

# === ACTION CUSTOMIZATION ===
# Only specify actions that need custom settings
actions:
  attack:
    dqn_profile: "exploration_focused"  # More exploration for combat learning
    rewards:
      success: 1.0
      kill: 5.0
      failure_penalty: -0.3
    costs:
      base: -0.2
    thresholds:
      defense: 0.3
      defense_boost: 2.0
      
  reproduce:
    rewards:
      success: 1.0
      offspring_survival: 0.5
    costs:
      failure_penalty: -0.2
      offspring_cost: 3
    thresholds:
      min_health: 0.5
      min_resources: 8

# === GLOBAL SETTINGS ===
# Core simulation parameters
starvation_threshold: 0
max_starvation_time: 15
starting_health: 100.0
attack_range: 20.0
perception_radius: 2

# === PERFORMANCE ===
use_in_memory_db: true
auto_optimize: true  # Automatically adjust settings based on system resources
db_profile: "fast"  # fast, balanced, safe

# === VISUALIZATION ===  
visualization:
  canvas_size: [400, 400]
  background_color: "black"
  agent_colors:
    SystemAgent: "blue"
    IndependentAgent: "red" 
    ControlAgent: "#DAA520"