version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis-benchmark
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --save 60 1 --loglevel warning
    restart: unless-stopped

volumes:
  redis-data:
    driver: local 