[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agentfarm"
version = "0.1.0"
description = "Agent Farm Simulation Framework"
readme = "README.md"

[tool.setuptools.packages.find]
where = ["."] 