experiment: redis_memory
params:
  # Quick validation parameters
  num_agents: 5
  memory_entries: 20
  batch_size: 5
  search_radius: 5.0
  memory_limit: 500
  ttl: 3600
  cleanup_interval: 20
iterations:
  warmup: 0
  measured: 1
instrumentation:
  - timing
  - psutil
output_dir: benchmarks/results/redis_memory
tags: [redis, memory, baseline]
notes: "Baseline Redis memory system performance"
seed: 42
