"""Training module for ML algorithms."""

from .collector import ExperienceCollector
from .crossover_search import (
    CrossoverRecipe,
    FineTuneRegime,
    LEADERBOARD_COLUMNS,
    ManifestEntry,
    SearchConfig,
    build_leaderboard,
    generate_recommendation,
    run_crossover_search,
)
from .crossover import (
    CROSSOVER_MODES,
    ChildArchitectureSpec,
    crossover_checkpoints,
    crossover_quantized_state_dict,
    initialize_child_from_crossover,
)
from .finetune import (
    FINETUNE_OPTIMIZERS,
    QUANTIZATION_APPLIED_MODES,
    FineTuner,
    FineTuningConfig,
    FineTuningMetrics,
    build_finetune_optimizer,
    load_finetuning_config_from_yaml,
)
from .quantize_ptq import (
    PostTrainingQuantizer,
    QuantizationConfig,
    QuantizationResult,
    QuantizedValidationReport,
    QuantizedValidationThresholds,
    QuantizedValidator,
    compare_outputs,
    load_quantized_checkpoint,
)
from .quantize_qat import (
    QATConfig,
    QATMetrics,
    QATTrainer,
    WeightOnlyFakeQuantLinear,
    load_qat_checkpoint,
)
from .recombination_eval import (
    REPORT_SCHEMA_VERSION,
    PairwiseComparison,
    RecombinationEvaluator,
    RecombinationReport,
    RecombinationThresholds,
)
from .holdout_utils import (
    SHIFT_TYPES,
    apply_gaussian_noise,
    apply_input_scaling,
    make_shifted_states,
    split_replay_buffer,
)
from .trainer import AlgorithmTrainer
from .distillation_rollout import (
    RolloutComparisonResult,
    SeededLinearMDP,
    compare_parent_student_rollouts,
    relative_return_drop,
)
from .sim_rollout_adapter import (
    EpisodeEnvProtocol,
    PolicyRolloutAdapter,
    SimEpisodeStats,
    SimRolloutConfig,
    SimRolloutResult,
)
from .memory_profiler import (
    PeakRAMSample,
    PipelineMemoryReport,
    StageMemoryProfile,
    profile_model_stage,
    profile_peak_ram,
)
from .trainer_distill import (
    DistillationConfig,
    DistillationMetrics,
    DistillationTrainer,
    StudentValidator,
    ValidationReport,
    ValidationThresholds,
)
from .label_metrics import (
    LabelMetrics,
    compute_label_metrics,
)
from .recombination_stats import (
    NUMERIC_METRIC_KEYS,
    BootstrapCIResult,
    ConditionSummary,
    TTestResult,
    aggregate_conditions,
    bootstrap_ci,
    compute_condition_summary,
    load_eval_reports,
    load_manifest_entries,
    paired_ttest,
    welch_ttest,
)

__all__ = [
    "AlgorithmTrainer",
    "apply_gaussian_noise",
    "apply_input_scaling",
    "aggregate_conditions",
    "bootstrap_ci",
    "BootstrapCIResult",
    "ConditionSummary",
    "compute_condition_summary",
    "CROSSOVER_MODES",
    "ChildArchitectureSpec",
    "CrossoverRecipe",
    "DistillationConfig",
    "DistillationMetrics",
    "DistillationTrainer",
    "EpisodeEnvProtocol",
    "ExperienceCollector",
    "FineTuneRegime",
    "FINETUNE_OPTIMIZERS",
    "FineTuner",
    "FineTuningConfig",
    "FineTuningMetrics",
    "LEADERBOARD_COLUMNS",
    "load_eval_reports",
    "load_manifest_entries",
    "ManifestEntry",
    "NUMERIC_METRIC_KEYS",
    "paired_ttest",
    "PairwiseComparison",
    "PolicyRolloutAdapter",
    "PostTrainingQuantizer",
    "QATConfig",
    "QATMetrics",
    "QATTrainer",
    "QUANTIZATION_APPLIED_MODES",
    "build_finetune_optimizer",
    "QuantizationConfig",
    "QuantizationResult",
    "QuantizedValidationReport",
    "QuantizedValidationThresholds",
    "QuantizedValidator",
    "PeakRAMSample",
    "PipelineMemoryReport",
    "StageMemoryProfile",
    "profile_model_stage",
    "profile_peak_ram",
    "REPORT_SCHEMA_VERSION",
    "RecombinationEvaluator",
    "RecombinationReport",
    "RecombinationThresholds",
    "RolloutComparisonResult",
    "SearchConfig",
    "SeededLinearMDP",
    "SimEpisodeStats",
    "SimRolloutConfig",
    "SimRolloutResult",
    "StudentValidator",
    "TTestResult",
    "ValidationReport",
    "ValidationThresholds",
    "LabelMetrics",
    "compute_label_metrics",
    "WeightOnlyFakeQuantLinear",
    "welch_ttest",
    "build_leaderboard",
    "compare_outputs",
    "compare_parent_student_rollouts",
    "crossover_checkpoints",
    "crossover_quantized_state_dict",
    "generate_recommendation",
    "initialize_child_from_crossover",
    "load_finetuning_config_from_yaml",
    "load_qat_checkpoint",
    "load_quantized_checkpoint",
    "make_shifted_states",
    "relative_return_drop",
    "run_crossover_search",
    "SHIFT_TYPES",
    "split_replay_buffer",
]
