# @package _global_
# Base Configuration
# This is the default configuration that serves as the foundation
# for all environment-specific overrides.

# Simulation settings
simulation_id: "base-simulation"
max_steps: 1000
environment: "base"

# Environment dimensions
width: 100
height: 100

# Agent settings
system_agents: 10
independent_agents: 10
control_agents: 10
initial_resource_level: 5
max_population: 300
starvation_threshold: 100
offspring_cost: 3
min_reproduction_resources: 8
offspring_initial_resources: 5
perception_radius: 2
base_attack_strength: 2
base_defense_strength: 2
seed: 1234567890

# Resource settings
initial_resources: 20
resource_regen_rate: 0.1
resource_regen_amount: 2
max_resource_amount: 30

# Agent behavior settings
base_consumption_rate: 0.15
max_movement: 8
gathering_range: 30
max_gather_amount: 3
territory_range: 30

# Learning parameters
learning_rate: 0.001
gamma: 0.95
epsilon_start: 1.0
epsilon_min: 0.01
epsilon_decay: 0.995
memory_size: 2000
batch_size: 32
training_frequency: 4
dqn_hidden_size: 24
tau: 0.005

# Combat parameters
starting_health: 100.0
attack_range: 20.0
attack_base_damage: 10.0
attack_kill_reward: 5.0

# Agent type ratios (must sum to 1.0)
agent_type_ratios:
  SystemAgent: 0.33
  IndependentAgent: 0.33
  ControlAgent: 0.34

# Agent-specific parameters
agent_parameters:
  SystemAgent:
    gather_efficiency_multiplier: 0.4
    gather_cost_multiplier: 0.4
    min_resource_threshold: 0.2
    share_weight: 0.3
    attack_weight: 0.05
  IndependentAgent:
    gather_efficiency_multiplier: 0.7
    gather_cost_multiplier: 0.2
    min_resource_threshold: 0.05
    share_weight: 0.05
    attack_weight: 0.25
  ControlAgent:
    gather_efficiency_multiplier: 0.55
    gather_cost_multiplier: 0.3
    min_resource_threshold: 0.125
    share_weight: 0.15
    attack_weight: 0.15

# Database configuration
use_in_memory_db: false
persist_db_on_completion: true
in_memory_db_memory_limit_mb: null
in_memory_tables_to_persist: null

# Database pragma settings
db_pragma_profile: "balanced"
db_cache_size_mb: 200
db_synchronous_mode: "NORMAL"
db_journal_mode: "WAL"
db_custom_pragmas: {}

# Redis configuration
redis:
  host: localhost
  port: 6379
  db: 0
  password: null
  decode_responses: true
  environment: default

# Visualization settings
visualization:
  canvas_size: [400, 400]
  padding: 20
  background_color: "black"
  max_animation_frames: 5
  animation_min_delay: 50
  max_resource_amount: 30
  resource_colors:
    glow_red: 50
    glow_green: 255
    glow_blue: 50
  resource_size: 2
  agent_radius_scale: 2
  birth_radius_scale: 4
  death_mark_scale: 1.5
  agent_colors:
    SystemAgent: "blue"
    IndependentAgent: "red"
    ControlAgent: "#DAA520"
  min_font_size: 10
  font_scale_factor: 40
  font_family: "arial"
  death_mark_color: [255, 0, 0]
  birth_mark_color: [255, 255, 255]
  metric_colors:
    total_agents: "#4a90e2"
    system_agents: "#50c878"
    independent_agents: "#e74c3c"
    control_agents: "#DAA520"
    total_resources: "#f39c12"
    average_agent_resources: "#9b59b6"

# Device configuration
device_preference: "auto"
device_fallback: true
device_memory_fraction: null
device_validate_compatibility: true