# Migration from Configuration Version 1.1 to 1.2
# This migration adds visualization configuration

from_version: "1.1"
to_version: "1.2"
description: "Add visualization configuration settings"
author: "Configuration Migration System"
date: "2024-01-20"

transformations:
  - operation: "add"
    target_path: "visualization"
    value:
      canvas_size: [400, 400]
      padding: 20
      background_color: "black"
      max_animation_frames: 5
      animation_min_delay: 50
      max_resource_amount: 30
      resource_colors:
        glow_red: 50
        glow_green: 255
        glow_blue: 50
      resource_size: 2
      agent_radius_scale: 2
      birth_radius_scale: 4
      death_mark_scale: 1.5
      agent_colors:
        SystemAgent: "blue"
        IndependentAgent: "red"
        ControlAgent: "#DAA520"
      min_font_size: 10
      font_scale_factor: 40
      font_family: "arial"
      death_mark_color: [255, 0, 0]
      birth_mark_color: [255, 255, 255]
      metric_colors:
        total_agents: "#4a90e2"
        system_agents: "#50c878"
        independent_agents: "#e74c3c"
        control_agents: "#DAA520"
        total_resources: "#f39c12"
        average_agent_resources: "#9b59b6"
    description: "Add comprehensive visualization configuration"

  - operation: "modify"
    source_path: "config_version"
    value: "1.2"
    description: "Update configuration version to 1.2"