# Migration from Configuration Version 1.2 to 2.0
# This migration adds Redis configuration and restructures some settings

from_version: "1.2"
to_version: "2.0"
description: "Add Redis configuration and restructure database settings"
author: "Configuration Migration System"
date: "2024-01-25"

transformations:
  - operation: "add"
    target_path: "redis"
    value:
      host: "localhost"
      port: 6379
      db: 0
      password: null
      decode_responses: true
      environment: "default"
    description: "Add Redis configuration section"

  - operation: "add"
    target_path: "use_in_memory_db"
    value: false
    description: "Add in-memory database flag"

  - operation: "add"
    target_path: "persist_db_on_completion"
    value: true
    description: "Add database persistence flag"

  - operation: "add"
    target_path: "in_memory_db_memory_limit_mb"
    value: null
    description: "Add memory limit for in-memory database"

  - operation: "add"
    target_path: "in_memory_tables_to_persist"
    value: null
    description: "Add tables to persist configuration"

  - operation: "add"
    target_path: "db_pragma_profile"
    value: "balanced"
    description: "Add database pragma profile setting"

  - operation: "add"
    target_path: "db_cache_size_mb"
    value: 200
    description: "Add database cache size setting"

  - operation: "add"
    target_path: "db_synchronous_mode"
    value: "NORMAL"
    description: "Add database synchronous mode setting"

  - operation: "add"
    target_path: "db_journal_mode"
    value: "WAL"
    description: "Add database journal mode setting"

  - operation: "add"
    target_path: "db_custom_pragmas"
    value: {}
    description: "Add custom database pragmas setting"

  - operation: "add"
    target_path: "device_preference"
    value: "auto"
    description: "Add device preference setting"

  - operation: "add"
    target_path: "device_fallback"
    value: true
    description: "Add device fallback setting"

  - operation: "add"
    target_path: "device_memory_fraction"
    value: null
    description: "Add device memory fraction setting"

  - operation: "add"
    target_path: "device_validate_compatibility"
    value: true
    description: "Add device compatibility validation setting"

  - operation: "modify"
    source_path: "config_version"
    value: "2.0"
    description: "Update configuration version to 2.0"