# Migration from Configuration Version 2.0 to 2.1
# This migration adds curriculum learning and advanced learning parameters

from_version: "2.0"
to_version: "2.1"
description: "Add curriculum learning and advanced learning parameters"
author: "Configuration Migration System"
date: "2024-02-01"

transformations:
  - operation: "add"
    target_path: "curriculum_phases"
    value:
      - steps: 100
        enabled_actions: ["move", "gather"]
      - steps: 200
        enabled_actions: ["move", "gather", "share", "attack"]
      - steps: -1
        enabled_actions: ["move", "gather", "share", "attack", "reproduce"]
    description: "Add curriculum learning phases"

  - operation: "add"
    target_path: "gather_target_update_freq"
    value: 100
    description: "Add gathering target update frequency"

  - operation: "add"
    target_path: "gather_memory_size"
    value: 10000
    description: "Add gathering memory size"

  - operation: "add"
    target_path: "gather_learning_rate"
    value: 0.001
    description: "Add gathering learning rate"

  - operation: "add"
    target_path: "gather_gamma"
    value: 0.99
    description: "Add gathering gamma"

  - operation: "add"
    target_path: "gather_epsilon_start"
    value: 1.0
    description: "Add gathering epsilon start"

  - operation: "add"
    target_path: "gather_epsilon_min"
    value: 0.01
    description: "Add gathering epsilon min"

  - operation: "add"
    target_path: "gather_epsilon_decay"
    value: 0.995
    description: "Add gathering epsilon decay"

  - operation: "add"
    target_path: "gather_dqn_hidden_size"
    value: 64
    description: "Add gathering DQN hidden size"

  - operation: "add"
    target_path: "gather_batch_size"
    value: 32
    description: "Add gathering batch size"

  - operation: "add"
    target_path: "gather_tau"
    value: 0.005
    description: "Add gathering tau"

  - operation: "add"
    target_path: "gather_success_reward"
    value: 0.5
    description: "Add gathering success reward"

  - operation: "add"
    target_path: "gather_failure_penalty"
    value: -0.1
    description: "Add gathering failure penalty"

  - operation: "add"
    target_path: "gather_base_cost"
    value: -0.05
    description: "Add gathering base cost"

  - operation: "add"
    target_path: "gather_distance_penalty_factor"
    value: 0.1
    description: "Add gathering distance penalty factor"

  - operation: "add"
    target_path: "gather_resource_threshold"
    value: 0.2
    description: "Add gathering resource threshold"

  - operation: "add"
    target_path: "gather_competition_penalty"
    value: -0.2
    description: "Add gathering competition penalty"

  - operation: "add"
    target_path: "gather_efficiency_bonus"
    value: 0.3
    description: "Add gathering efficiency bonus"

  - operation: "modify"
    source_path: "config_version"
    value: "2.1"
    description: "Update configuration version to 2.1"