# Staging Environment Configuration
# Overrides for staging environment

# Moderate debug settings
debug: false
verbose_logging: true

# Production-like simulation settings
max_steps: 500
max_population: 200

# Use persistent database for staging
use_in_memory_db: false
persist_db_on_completion: true

# Staging-specific learning parameters
learning_rate: 0.005
epsilon_start: 0.8
epsilon_min: 0.05

# Moderate resource settings
initial_resources: 15
resource_regen_rate: 0.15

# Staging database settings
db_pragma_profile: "balanced"
db_cache_size_mb: 100

# Staging Redis settings
redis:
  host: staging-redis.example.com
  port: 6379
  db: 0
  environment: staging