name: Deterministic Simulation Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deterministic-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install package
      run: |
        pip install -e .
        
    - name: Run deterministic simulation test
      run: |
        python tests/test_deterministic.py --environment testing --steps 50 --seed 42
        
    - name: Run extended deterministic test
      run: |
        python tests/test_deterministic.py --environment testing --steps 100 --seed 123
