name: Redis Memory Benchmark

on:
  push:
    branches: [ main ]
    paths:
      - 'farm/memory/redis_memory.py'
      - 'farm/database/memory.py'
      - '.github/workflows/redis_benchmark.yml'
  workflow_dispatch:  # Allow manual triggering
  
jobs:
  benchmark:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install redis matplotlib pandas numpy
          pip install -r requirements.txt || echo "No requirements.txt file found"
      
      - name: Run benchmark with different batch sizes
        run: |
          mkdir -p benchmark_results
          
          # Run benchmarks with different batch sizes
          python simple_redis_benchmark.py --memory-entries 500 --batch-size 10 --output benchmark_results/batch_10.json
          python simple_redis_benchmark.py --memory-entries 500 --batch-size 100 --output benchmark_results/batch_100.json
          python simple_redis_benchmark.py --memory-entries 500 --batch-size 500 --output benchmark_results/batch_500.json
          
          # Generate visualizations
          python advanced_charts.py benchmark_results/batch_10.json benchmark_results/batch_100.json benchmark_results/batch_500.json
      
      - name: Track performance changes
        run: |
          # Create a history entry in case there's no history file yet
          python track_performance.py add benchmark_results/batch_100.json --note "Auto benchmark from GitHub Actions"
          
          # Generate performance history chart
          python track_performance.py plot
      
      - name: Archive benchmark results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: |
            benchmark_results/
            charts/
            performance_history.png
            redis_performance_history.json
      
      - name: Update benchmark results in repo
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Configure git
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Create benchmark results directory if it doesn't exist
          mkdir -p benchmark_data
          
          # Copy the latest results
          cp benchmark_results/*.json benchmark_data/
          cp -r charts benchmark_data/ || mkdir -p benchmark_data/charts
          cp performance_history.png benchmark_data/ || echo "No performance history chart found"
          cp redis_performance_history.json benchmark_data/ || echo "No performance history file found"
          
          # Create summary markdown file
          echo "# Redis Memory Benchmark Results" > benchmark_data/README.md
          echo "Last updated: $(date)" >> benchmark_data/README.md
          echo "" >> benchmark_data/README.md
          echo "## Performance Summary" >> benchmark_data/README.md
          echo "Here are the latest benchmark results:" >> benchmark_data/README.md
          echo "" >> benchmark_data/README.md
          echo "- Batch Size 10: $(python -c "import json; print(json.load(open('benchmark_results/batch_10.json'))['overall']['batch_throughput'])")" >> benchmark_data/README.md
          echo "- Batch Size 100: $(python -c "import json; print(json.load(open('benchmark_results/batch_100.json'))['overall']['batch_throughput'])")" >> benchmark_data/README.md
          echo "- Batch Size 500: $(python -c "import json; print(json.load(open('benchmark_results/batch_500.json'))['overall']['batch_throughput'])")" >> benchmark_data/README.md
          echo "" >> benchmark_data/README.md
          echo "## Charts" >> benchmark_data/README.md
          echo "![Batch Size Comparison](charts/batch_size_throughput.png)" >> benchmark_data/README.md
          echo "![Operation Comparison](charts/comparison_bar.png)" >> benchmark_data/README.md
          echo "![Performance History](performance_history.png)" >> benchmark_data/README.md
          
          # Commit and push
          git add benchmark_data
          git commit -m "Update benchmark results [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 