name: tests

on:
	push:
		branches: [ main ]
	pull_request:
		branches: [ main ]

jobs:
	python:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v4
			- uses: actions/setup-python@v5
			  with:
				python-version: '3.10'
			- name: Install Python deps
			  run: |
				python -m pip install --upgrade pip
				pip install -r requirements.txt
			- name: Run pytest
			  run: |
				pytest -q --cov=farm --cov-report=term-missing

	js-ui:
		runs-on: ubuntu-latest
		defaults:
			run:
				working-directory: farm/editor
		steps:
			- uses: actions/checkout@v4
			- uses: actions/setup-node@v4
			  with:
				node-version: '20'
			- name: Install
			  run: npm ci || npm install --no-audit --no-fund
			- name: Run Jest
			  run: npm test -- --runInBand

